name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js, NPM, and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build production files
        run: npm run build
      - name: Commit production files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          message: 'FEAT (TEST) Testing commit'
